name: 'yearplusplus'
description: 'Update year in specified files and commit changes to Git'
author: 'Endormi'
inputs:
  files:
    description: 'Files to update'
    required: true
  last_year:
    description: 'Custom last year'
    required: false
  current_year:
    description: 'Custom current year'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Files to update: ${{ inputs.files }}"
        files="${{ inputs.files }}"
        from_year="${{ inputs.last_year }}"
        to_year="${{ inputs.current_year }}"

        if [ -z "$from_year" ]; then
          from_year=$(date --date="1 year ago" +%Y)
        fi

        if [ -z "$to_year" ]; then
          to_year=$(date +%Y)
        fi
        find $files -exec sed -i "s/${from_year}/${to_year}/g" {} \;
      shell: bash
