name: 'yearplusplus'
description: 'Update year in specified files and commit changes to Git'
author: 'Endormi'
inputs:
  files:
    description: 'Files to update'
    required: true
  last_year:
    description: 'Custom last year'
    required: false
  current_year:
    description: 'Custom current year'
    required: false
  git_user:
    description: 'Git username'
    required: false
    default: 'Year++'
  git_email:
    description: 'Git email'
    required: false
    default: '<>'
  commit_message:
    description: 'Commit message'
    required: false
    default: 'Update copyright year'
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Files to update: ${{ inputs.files }}"
        files="${{ inputs.files }}"
        last_year="${{ inputs.last_year }}"
        current_year="${{ inputs.current_year }}"

        if [ -z "$last_year" ]; then
          last_year=$(date --date="1 year ago" +%Y)
        fi

        if [ -z "$current_year" ]; then
          current_year=$(date +%Y)
        fi
        find $files -exec sed -i "s/${last_year}/${current_year}/g" {} \;
      shell: bash
    - name: Setup Git configuration
      run: |
        git_user="${{ inputs.git_user }}"
        if [ -z "$git_user" ]; then
          git_user="Year++"
        fi
        git_email="${{ inputs.git_email }}"
        if [ -z "$git_email" ]; then
          git_email="<>"
        fi
        git config user.name "$git_user"
        git config user.email "$git_email"
      shell: bash
    - name: Commit changes
      run: |
        commit_message="${{ inputs.commit_message }}"
        if [ -z "$commit_message" ]; then
          commit_message="Update copyright year"
        fi
        git commit -am "$commit_message"
        git push origin ${{ github.ref }}
      shell: bash
