name: 'yearplusplus'
description: 'Update year in specified files and commit changes to Git'
author: 'Endormi'
inputs:
  files:
    description: 'Files to update'
    required: true
  username:
    description: 'Username for the commit'
    required: false
    type: string
    default: 'github-actions[bot]'
  email:
    description: 'Email for the commit'
    required: false
    type: string
    default: 'github-actions[bot]@users.noreply.github.com'
  commit_message:
    description: 'Commit message'
    required: false
    type: string
    default: 'Update copyright year'
  last_year:
    description: 'Custom last year'
    required: false
  current_year:
    description: 'Custom current year'
    required: false
runs:
  using: 'composite'
  steps:
    - run: |
        echo "Files to update: ${{ inputs.files }}"
        files="${{ inputs.files }}"
        from_year="${{ inputs.last_year }}"
        to_year="${{ inputs.current_year }}"

        if [ -z "$from_year" ]; then
          from_year=$(date --date="1 year ago" +%Y)
        fi

        if [ -z "$to_year" ]; then
          to_year=$(date +%Y)
        fi
        find $files -exec sed -i "s/${from_year}/${to_year}/g" {} \;
      shell: bash

    - run: |
        git config user.name "${{ inputs.username }}"
        git config user.email "${{ inputs.email }}"
        if [ -n "$(git status --porcelain)" ]; then
            git commit -am "${{ inputs.commit_message }}"
            git push origin ${{ github.head_ref }}
          else
            echo "No changes to commit."
          fi
      shell: bash